[project]
name = "hancom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1",
    "easyocr>=1.7",
    "numpy>=1.24",
    "opencv-python>=4.8",
    "Pillow>=10",
    "pyautogui>=0.9.54",
    "pyhwpx>=1.6.6",
    "pymupdf>=1.24",
    "scikit-image>=0.21",
]
